### ISSUE TITLE
Journald is setup with Storage=ephemeral making debuging installs freezing on boot REALLY hard 

### ISSUE THREAD

**Issue by c2h5oh** [endeavouros-team/calamares-offlineinstaller#5]
**Describe the bug**
Journald is configured with ephemeral (in-memory only) storage. If you ie boot from usb stick to see why your install is freezing on boot you will find no logs, because none are persisted.

**To Reproduce**
Default install.

**Expected behavior**
`/etc/systemd/journald.conf` contains `Storage=persistent` which results in logs being preserved in case you need to debug boot failure.

**Additional context**
Looking at my other Arch install (Antergos) this is not default - that line is commented out / set to auto

**Comment by killajoe** [comment]
https://www.freedesktop.org/software/systemd/man/journald.conf.html

it is set to `Storage=volatile`  
Afaik we do not set up to do so, it is may default on calamares?  @Portergos ?

**Comment by killajoe** [comment]
tracked it down it was this part of the script, but we do not read it right ;)
it is needed for the Live session, and will be resolved on installed system now...
